spring:
  application:
    name: weatherstation

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mqtt:
  broker-url: ${MQTT_BROKER_URL}
  topic: ${MQTT_TOPIC}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}

server:
  port: 5000